import { WorkspaceAuthorisationService } from "./authorisation-service";
import { createOneTimeCode, createOpaqueId, deriveLocalVerifier, matchesLocalVerifier, type LocalVerifier } from "./local-secret-verifier";
import type { StorageBoundary } from "./local-identity-provider";
import type { WorkspaceRepository } from "./workspace-repository";
import { InvitationSchema, MembershipAuditEventSchema, OrganisationMembershipSchema, OrganisationSchema, WORKSPACE_CONTRACT_VERSION, type Invitation, type MembershipAuditEvent, type Organisation, type OrganisationMembership, type UserAccount, type WorkspaceRole } from "./workspace-schema";

export const LOCAL_WORKSPACE_STORAGE_KEY = "oet:workspace:v1:governance";
type StoredInvitation = Invitation & { codeVerifier: LocalVerifier };
type WorkspaceState = { organisations: Organisation[]; memberships: OrganisationMembership[]; invitations: StoredInvitation[]; audit: MembershipAuditEvent[] };
const emptyState = (): WorkspaceState => ({ organisations: [], memberships: [], invitations: [], audit: [] });

export class LocalWorkspaceRepository implements WorkspaceRepository {
  private readonly auth = new WorkspaceAuthorisationService();
  constructor(private readonly storage: StorageBoundary, private readonly now: () => Date = () => new Date()) {}
  private read(): WorkspaceState {
    const raw = this.storage.getItem(LOCAL_WORKSPACE_STORAGE_KEY); if (!raw) return emptyState();
    try { const state = JSON.parse(raw) as WorkspaceState; return { organisations: (state.organisations || []).map((x) => OrganisationSchema.parse(x)), memberships: (state.memberships || []).map((x) => OrganisationMembershipSchema.parse(x)), invitations: (state.invitations || []).map((x) => ({ ...InvitationSchema.parse(x), codeVerifier: x.codeVerifier })), audit: (state.audit || []).map((x) => MembershipAuditEventSchema.parse(x)) }; } catch { return emptyState(); }
  }
  private write(state: WorkspaceState) { this.storage.setItem(LOCAL_WORKSPACE_STORAGE_KEY, JSON.stringify(state)); }
  private membership(state: WorkspaceState, organisationId: string, userId: string) { return state.memberships.find((item) => item.organisationId === organisationId && item.userId === userId && item.status === "active"); }
  private require(state: WorkspaceState, organisationId: string, userId: string, permission: Parameters<WorkspaceAuthorisationService["evaluate"]>[1]) { const decision = this.auth.evaluate(this.membership(state, organisationId, userId), permission); if (!decision.allowed) throw new Error(decision.reason); return this.membership(state, organisationId, userId)!; }
  private audit(state: WorkspaceState, organisationId: string, actorUserId: string, event: MembershipAuditEvent["event"], targetId: string, detail: string) { state.audit.unshift(MembershipAuditEventSchema.parse({ contractVersion: WORKSPACE_CONTRACT_VERSION, id: createOpaqueId("aud"), organisationId, actorUserId, event, targetId, at: this.now().toISOString(), detail })); }

  async createOrganisation(actor: UserAccount, name: string) {
    const state = this.read(); const stamp = this.now().toISOString(); const cleanName = name.trim();
    const baseSlug = cleanName.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "workspace";
    const organisation = OrganisationSchema.parse({ contractVersion: WORKSPACE_CONTRACT_VERSION, id: createOpaqueId("org"), name: cleanName, slug: `${baseSlug}-${crypto.getRandomValues(new Uint16Array(1))[0].toString(36)}`, status: "active", createdByUserId: actor.id, createdAt: stamp, updatedAt: stamp });
    const membership = OrganisationMembershipSchema.parse({ contractVersion: WORKSPACE_CONTRACT_VERSION, id: createOpaqueId("mem"), organisationId: organisation.id, userId: actor.id, role: "owner", status: "active", createdAt: stamp, updatedAt: stamp });
    state.organisations.push(organisation); state.memberships.push(membership); this.audit(state, organisation.id, actor.id, "organisation.created", organisation.id, "Organisation created with first active owner."); this.write(state); return { organisation, membership };
  }
  async listOrganisations(userId: string) { const state = this.read(); const ids = new Set(state.memberships.filter((x) => x.userId === userId && x.status === "active").map((x) => x.organisationId)); return state.organisations.filter((x) => ids.has(x.id) && x.status === "active"); }
  async listMemberships(organisationId: string, actorUserId: string) { const state = this.read(); this.require(state, organisationId, actorUserId, "organisation.read"); return state.memberships.filter((x) => x.organisationId === organisationId && x.status === "active"); }
  async listInvitations(organisationId: string, actorUserId: string) { const state = this.read(); this.require(state, organisationId, actorUserId, "invitation.create"); return state.invitations.filter((x) => x.organisationId === organisationId).map((x) => InvitationSchema.parse(x)); }
  async createInvitation(organisationId: string, actorUserId: string, email: string, role: WorkspaceRole) { const state = this.read(); const actor = this.require(state, organisationId, actorUserId, "invitation.create"); const assignment = this.auth.canAssignRole(actor.role, role); if (!assignment.allowed) throw new Error(assignment.reason); const stamp = this.now(); const code = createOneTimeCode(); const invitation = InvitationSchema.parse({ contractVersion: WORKSPACE_CONTRACT_VERSION, id: createOpaqueId("inv"), organisationId, email: email.trim().toLowerCase(), role, invitedByUserId: actorUserId, status: "pending", expiresAt: new Date(stamp.getTime() + 7 * 86400000).toISOString(), createdAt: stamp.toISOString() }); state.invitations.push({ ...invitation, codeVerifier: await deriveLocalVerifier(code) }); this.audit(state, organisationId, actorUserId, "invitation.created", invitation.id, `Invitation issued for ${role}.`); this.write(state); return { invitation, code }; }
  async revokeInvitation(organisationId: string, actorUserId: string, invitationId: string) { const state = this.read(); this.require(state, organisationId, actorUserId, "invitation.create"); const invitation = state.invitations.find((x) => x.id === invitationId && x.organisationId === organisationId && x.status === "pending"); if (!invitation) throw new Error("The invitation is not available."); invitation.status = "revoked"; this.audit(state, organisationId, actorUserId, "invitation.revoked", invitation.id, "Pending invitation revoked."); this.write(state); return InvitationSchema.parse(invitation); }
  async acceptInvitation(account: UserAccount, code: string) { const state = this.read(); let invitation: StoredInvitation | undefined; for (const item of state.invitations.filter((x) => x.status === "pending")) if (await matchesLocalVerifier(code, item.codeVerifier)) { invitation = item; break; } if (!invitation || invitation.email !== account.email || new Date(invitation.expiresAt).getTime() <= this.now().getTime()) throw new Error("The invitation is not valid or is no longer available."); const stamp = this.now().toISOString(); invitation.status = "accepted"; invitation.acceptedAt = stamp; const membership = OrganisationMembershipSchema.parse({ contractVersion: WORKSPACE_CONTRACT_VERSION, id: createOpaqueId("mem"), organisationId: invitation.organisationId, userId: account.id, role: invitation.role, status: "active", invitationId: invitation.id, createdAt: stamp, updatedAt: stamp }); state.memberships.push(membership); this.audit(state, invitation.organisationId, account.id, "invitation.accepted", invitation.id, `Invitation accepted as ${invitation.role}.`); this.write(state); return { invitation: InvitationSchema.parse(invitation), membership }; }
  async updateMembershipRole(organisationId: string, actorUserId: string, membershipId: string, role: WorkspaceRole) { const state = this.read(); const actor = this.require(state, organisationId, actorUserId, "membership.manage"); const assignment = this.auth.canAssignRole(actor.role, role); if (!assignment.allowed) throw new Error(assignment.reason); const target = state.memberships.find((x) => x.id === membershipId && x.organisationId === organisationId && x.status === "active"); if (!target) throw new Error("Active membership not found."); if (target.role === "owner" && role !== "owner" && state.memberships.filter((x) => x.organisationId === organisationId && x.status === "active" && x.role === "owner").length <= 1) throw new Error("An organisation must retain at least one active owner."); target.role = role; target.updatedAt = this.now().toISOString(); this.audit(state, organisationId, actorUserId, "membership.role_changed", target.id, `Membership role changed to ${role}.`); this.write(state); return OrganisationMembershipSchema.parse(target); }
  async removeMembership(organisationId: string, actorUserId: string, membershipId: string) { const state = this.read(); this.require(state, organisationId, actorUserId, "membership.manage"); const target = state.memberships.find((x) => x.id === membershipId && x.organisationId === organisationId && x.status === "active"); if (!target) throw new Error("Active membership not found."); if (target.role === "owner" && state.memberships.filter((x) => x.organisationId === organisationId && x.status === "active" && x.role === "owner").length <= 1) throw new Error("An organisation must retain at least one active owner."); target.status = "suspended"; target.updatedAt = this.now().toISOString(); this.audit(state, organisationId, actorUserId, "membership.removed", target.id, "Membership removed."); this.write(state); }
  async listAudit(organisationId: string, actorUserId: string) { const state = this.read(); this.require(state, organisationId, actorUserId, "organisation.manage"); return state.audit.filter((x) => x.organisationId === organisationId); }
}
