import { expect, test } from "@playwright/test";

test("changes the password and restores an encrypted workspace after destructive reset", async ({ page }) => {
  await page.goto("/?view=register"); await page.getByLabel("Display name").fill("Safety Owner"); await page.getByLabel("Email").fill("safety.owner@example.com"); await page.getByLabel("Local demonstration password").fill("original-local-password"); await page.getByRole("checkbox").check(); await page.getByRole("button", { name: "Create local account" }).click();
  await page.getByLabel("Organisation name").fill("Safety Portfolio"); await page.getByRole("button", { name: "Create organisation" }).click(); await page.getByLabel("Project name").fill("Recoverable Project"); await page.getByRole("button", { name: "Create project" }).click();
  await expect(page.getByRole("heading", { name: "Browser-local safety centre" })).toBeVisible();
  const passwordCard = page.locator(".safety-card").filter({ hasText: "Change local password" }); await passwordCard.getByLabel("Current local password").fill("original-local-password"); await passwordCard.getByLabel("New local password").fill("replacement-local-password"); await passwordCard.getByLabel("Confirm new password").fill("replacement-local-password"); await passwordCard.getByRole("button", { name: "Change password" }).click(); await expect(page.getByText("The previous password is no longer valid.")).toBeVisible();
  const backupCard = page.locator(".safety-card").filter({ hasText: "Export encrypted workspace" }); await backupCard.getByLabel("Dedicated backup passphrase").fill("dedicated-backup-passphrase"); await backupCard.getByLabel("Confirm backup passphrase").fill("dedicated-backup-passphrase"); const downloadPromise = page.waitForEvent("download"); await backupCard.getByRole("button", { name: "Download encrypted backup" }).click(); const download = await downloadPromise; const backupPath = await download.path(); expect(backupPath).toBeTruthy();
  await page.getByLabel(/Type DELETE LOCAL MVP DATA/).fill("DELETE LOCAL MVP DATA"); await page.getByRole("button", { name: "Delete all local MVP data" }).click(); await expect(page.getByRole("heading", { name: "Start your transformation workspace." })).toBeVisible();
  await page.getByRole("button", { name: "Already registered? Sign in" }).click(); const restore = page.locator(".backup-restore.compact"); await restore.getByLabel("Encrypted backup file").setInputFiles(backupPath!); await restore.getByLabel("Dedicated backup passphrase").fill("dedicated-backup-passphrase"); await restore.getByRole("button", { name: "Preview backup" }).click(); await expect(restore.getByText(/1 account.*1 organisation.*1 project/)).toBeVisible(); await restore.getByRole("button", { name: "Restore validated backup" }).click();
  await page.getByLabel("Email").fill("safety.owner@example.com"); await page.getByLabel("Local demonstration password").fill("replacement-local-password"); await page.getByRole("button", { name: "Sign in" }).click(); await expect(page.getByRole("heading", { name: "Safety Portfolio" })).toBeVisible(); await expect(page.locator(".project-workspaces").getByRole("heading", { name: "Recoverable Project" })).toBeVisible();
});
