"use client";

import { useState } from "react";
import type { IdentityProvider } from "@/lib/identity-provider";
import type { Session, UserAccount } from "@/lib/workspace-schema";
import { deleteAgentOperationsDatabase, exportAllAgentOperationRecords } from "@/lib/agent-operations-store";
import { clearLocalWorkspaceStorage, createEncryptedLocalBackup, localStorageStatus, markLocalBackupCreated } from "@/lib/local-workspace-backup";
import { BackupRestoreControl } from "./backup-restore-control";

const RESET_CONFIRMATION = "DELETE LOCAL MVP DATA";
function formatBytes(bytes: number) { return bytes < 1024 ? `${bytes} B` : `${(bytes / 1024).toFixed(1)} KB`; }

export function AccountSafetyPanel({ account, session, provider, onReset }: { account: UserAccount; session: Session; provider: IdentityProvider; onReset: () => void }) {
  const [status, setStatus] = useState<ReturnType<typeof localStorageStatus> | null>(() => typeof window === "undefined" ? null : localStorageStatus(window.localStorage)); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [resetText, setResetText] = useState("");
  async function changePassword(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); setMessage(""); const form = event.currentTarget; const values = new FormData(form); const next = String(values.get("newPassword") || ""); if (next !== String(values.get("confirmPassword") || "")) { setError("New password confirmation does not match."); setBusy(false); return; } try { await provider.changePassword(String(values.get("currentPassword") || ""), next); form.reset(); setMessage("Local password changed. The previous password is no longer valid."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Password change failed."); } finally { setBusy(false); } }
  async function exportBackup(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); setMessage(""); const form = event.currentTarget; const values = new FormData(form); const passphrase = String(values.get("backupPassphrase") || ""); if (passphrase !== String(values.get("backupPassphraseConfirm") || "")) { setError("Backup passphrase confirmation does not match."); setBusy(false); return; } try { const serialized = await createEncryptedLocalBackup(window.localStorage, passphrase, await exportAllAgentOperationRecords()); const blob = new Blob([serialized], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `transformation-cockpit-${new Date().toISOString().slice(0, 10)}.oetbackup`; link.click(); URL.revokeObjectURL(link.href); markLocalBackupCreated(window.localStorage); setStatus(localStorageStatus(window.localStorage)); form.reset(); setMessage("Encrypted local backup created. Store the file and its separate passphrase safely."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Backup export failed."); } finally { setBusy(false); } }
  async function reset() { if (resetText !== RESET_CONFIRMATION) return; setBusy(true); setError(""); try { clearLocalWorkspaceStorage(window.localStorage); await deleteAgentOperationsDatabase(); onReset(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Local reset failed."); setBusy(false); } }
  return <section className="account-safety" aria-labelledby="account-safety-title"><header><div><span className="public-kicker">LOCAL ACCOUNT & DATA</span><h2 id="account-safety-title">Browser-local safety centre</h2></div><b>Development mode</b></header>
    <div className="local-boundary-summary"><dl><div><dt>Active account</dt><dd>{account.displayName}<small>{account.email}</small></dd></div><div><dt>Session expires</dt><dd>{new Date(session.expiresAt).toLocaleString("en-GB")}</dd></div><div><dt>Local storage</dt><dd>{status ? `${status.keys} records · ${formatBytes(status.bytes)}` : "Calculating…"}</dd></div><div><dt>Last backup</dt><dd>{status?.metadata.lastBackupAt ? new Date(status.metadata.lastBackupAt).toLocaleString("en-GB") : "No backup recorded"}</dd></div></dl><p>This account and its projects exist only in this browser profile. Passwords cannot be displayed or recovered. Clearing browser data can permanently remove local work.</p></div>
    {error && <div className="error-banner" role="alert">{error}</div>}{message && <div className="success-banner" role="status">{message}</div>}
    <div className="account-safety-grid"><form className="safety-card" onSubmit={changePassword}><span className="public-kicker">PASSWORD</span><h3>Change local password</h3><p>The current password must be verified. This does not create a recovery mechanism.</p><label><span>Current local password</span><input name="currentPassword" type="password" required minLength={10} autoComplete="current-password" /></label><label><span>New local password</span><input name="newPassword" type="password" required minLength={10} autoComplete="new-password" /></label><label><span>Confirm new password</span><input name="confirmPassword" type="password" required minLength={10} autoComplete="new-password" /></label><button className="public-outline-button" disabled={busy}>Change password</button></form>
      <form className="safety-card" onSubmit={exportBackup}><span className="public-kicker">BACKUP</span><h3>Export encrypted workspace</h3><p>Includes local account verifiers, organisations, projects, PMO documents and non-secret agent run records. Active sessions and recovery evidence files are excluded.</p><label><span>Dedicated backup passphrase</span><input name="backupPassphrase" type="password" required minLength={12} autoComplete="off" /></label><label><span>Confirm backup passphrase</span><input name="backupPassphraseConfirm" type="password" required minLength={12} autoComplete="off" /></label><button className="public-button" disabled={busy}>Download encrypted backup</button></form>
    </div>
    <BackupRestoreControl onRestored={() => window.location.reload()} />
    <section className="danger-zone"><span className="public-kicker">DESTRUCTIVE RESET</span><h3>Remove every local cockpit account and workspace</h3><p>This removes all local identities, organisations, memberships, projects, PMO documents, selection state and agent-operation records in this browser. Current local impact: {status ? `${status.inventory.accounts} account(s), ${status.inventory.organisations} organisation(s), ${status.inventory.projects} project(s) and ${status.inventory.projectDocuments} stored PMO document(s)` : "calculating local records"}, plus the agent-operation store. Export a verified backup first.</p><label><span>Type <code>{RESET_CONFIRMATION}</code> to confirm</span><input value={resetText} onChange={(event) => setResetText(event.target.value)} /></label><button type="button" disabled={busy || resetText !== RESET_CONFIRMATION} onClick={() => void reset()}>Delete all local MVP data</button></section>
  </section>;
}
