import type { AgentRunEnvelope } from "@/lib/agent-contracts";
import qualityReport from "@/data/agent-quality-report.json";
import liveQualityReport from "@/data/agent-live-quality-report.json";
import orchestrationReport from "@/data/orchestration-quality-report.json";
import { AGENT_CATALOGUE, diagnoseWorkflowCompatibility } from "@/lib/agent-control-plane";
import runtimeReport from "@/data/lean-runtime-performance-report.json";
import accuracyReport from "@/data/agent-accuracy-hardening-report.json";
import { summarizeAgentHealth } from "@/lib/agent-health";

export function OperationalHealth({ runs, pendingReviews }: { runs: Array<{ run: AgentRunEnvelope }>; pendingReviews: number }) {
  const health = summarizeAgentHealth(runs.map((entry) => entry.run));
  const compatibility = AGENT_CATALOGUE.map((entry) => diagnoseWorkflowCompatibility(entry, { releaseId: entry.releaseId, liveBindingId: entry.liveBindingId }));
  const failed = runs.filter((entry) => entry.run.status === "failed");
  const incidents = [
    ...(failed.length ? [{ severity: "critical", title: `${failed.length} failed agent execution${failed.length === 1 ? "" : "s"}`, action: "Open Agent operations, assign an owner and retry or replay only after inspecting the failed step." }] : []),
    ...(pendingReviews ? [{ severity: "warning", title: `${pendingReviews} proposal set${pendingReviews === 1 ? "" : "s"} awaiting review`, action: "Complete accountable review before publication." }] : []),
  ];
  return <div className="ops-health">
    <section className="ops-health-grid">
      <article className="panel"><span className="section-kicker">RELEASE</span><h3>{AGENT_CATALOGUE[0]?.releaseId}</h3><p>Checksummed baseline · {compatibility.every((item) => item.status === "compatible") ? "catalogue bindings compatible" : "binding verification required"}</p><strong className={compatibility.every((item) => item.status === "compatible") ? "health-ok" : "health-warning"}>{compatibility.every((item) => item.status === "compatible") ? "Release ready" : "Publication blocked"}</strong></article>
      <article className="panel"><span className="section-kicker">AGENT QUALITY</span><h3>{qualityReport.caseCount} deterministic + {liveQualityReport.caseCount} live cases</h3><p>{liveQualityReport.formats.join(" · ")} · {Math.round(liveQualityReport.scores.fieldAccuracy * 100)}% critical-field accuracy · P95 {Math.round(liveQualityReport.scores.p95LatencyMs / 1000)}s</p><strong className={qualityReport.releaseReady && liveQualityReport.releaseReady ? "health-ok" : "health-warning"}>{qualityReport.releaseReady && liveQualityReport.releaseReady ? "Dual gate passed" : "Promotion blocked"}</strong></article>
      <article className="panel"><span className="section-kicker">SMART ROUTING</span><h3>{Math.round(orchestrationReport.improvements.costReduction * 100)}% less execution</h3><p>{orchestrationReport.candidate.calls}/{orchestrationReport.baseline.calls} specialist calls · {orchestrationReport.precision * 100}% precision · {orchestrationReport.recall * 100}% recall</p><strong className={orchestrationReport.qualityGatePassed ? "health-ok" : "health-warning"}>{orchestrationReport.qualityGatePassed ? "Quality preserved" : "Promotion blocked"}</strong></article>
      <article className="panel"><span className="section-kicker">LIVE RUN HEALTH</span><h3>{Math.round(health.successRate * 100)}% success</h3><p>{health.total} runs · P50 {Math.round(health.p50LatencyMs / 1000)}s · P95 {Math.round(health.p95LatencyMs / 1000)}s · {health.staleRuns} stale</p><strong className={health.staleRuns || health.successRate < .99 ? "health-warning" : "health-ok"}>{health.staleRuns ? "Reconciliation required" : "Within lifecycle policy"}</strong></article>
    </section>
    <section className="panel ops-policy"><div><span>Routine runtime gate</span><b>P50 {runtimeReport.routine.p50Ms} ms · P95 {runtimeReport.routine.p95Ms} ms</b></div><div><span>Accuracy hardening</span><b>{accuracyReport.caseCount} cases · {Math.round(accuracyReport.scores.criticalFieldAccuracy * 100)}% critical fields</b></div><div><span>Runtime classes</span><b>{Object.entries(health.byRuntimeClass).map(([key, value]) => `${key} ${value}`).join(" · ") || "No runs"}</b></div><div><span>Failure categories</span><b>{Object.entries(health.byFailureCode).map(([key, value]) => `${key} ${value}`).join(" · ") || "None"}</b></div></section>
    <section className="panel ops-health-section"><header><span className="section-kicker">VERSIONED AGENT CATALOGUE</span><h2>Authoritative n8n control plane</h2><p>Every agent declares its purpose, immutable release and live binding. Project content is confidential; operational metadata remains redacted.</p></header><div className="agent-catalogue">{AGENT_CATALOGUE.map((agent) => { const diagnostic = diagnoseWorkflowCompatibility(agent, { releaseId: agent.releaseId, liveBindingId: agent.liveBindingId }); return <article key={agent.workflowId}><span className="health-dot"/><div><b>{agent.title}</b><p>{agent.purpose}</p><small>{agent.workflowId} · v{agent.workflowVersion} · {agent.dataClassification.replaceAll("_", " ")} · {agent.writeBoundary.replaceAll("_", " ")}</small></div><code>{agent.liveBindingId}</code><strong className={diagnostic.status === "compatible" ? "health-ok" : "health-warning"}>{diagnostic.status.replaceAll("_", " ")}</strong></article>; })}</div><footer className="activation-guidance"><b>Browser-session activation</b><p>Sign in to the existing n8n tenant in your own browser, then run <code>npm run bind:agent-workflows</code> and <code>npm run verify:governance-artifacts</code>. The scripts compare IDs, releases and checksums; they never request or export credentials or MFA codes. A stale or unknown binding blocks publication and follows the support runbook.</p></footer></section>
    <section className="panel ops-health-section quality-health"><header><div><span className="section-kicker">EVALUATION READINESS</span><h2>Deterministic and live n8n quality</h2><p>{qualityReport.candidate.name} is compared with {qualityReport.baseline.name} across {qualityReport.caseCount} cases; {liveQualityReport.caseCount} sanitized live captures verify the authoritative orchestrator v{liveQualityReport.release.orchestratorVersion}. Blocking regressions prevent promotion.</p></div><strong className={qualityReport.releaseReady && liveQualityReport.releaseReady ? "health-ok" : "health-warning"}>{qualityReport.releaseReady && liveQualityReport.releaseReady ? "Release ready" : "Blocked"}</strong></header><div className="quality-score-grid">{[["Live precision", liveQualityReport.scores.objectPrecision], ["Live recall", liveQualityReport.scores.objectRecall], ["Field accuracy", liveQualityReport.scores.fieldAccuracy], ["Evidence attribution", liveQualityReport.scores.evidenceAttribution]].map(([name, score]) => <article key={String(name)}><span>{name}</span><b>{Math.round(Number(score) * 100)}%</b><small>Live baseline</small></article>)}</div><div className="quality-agent-grid"><div className="quality-agent-head"><b>Specialist</b><b>Cases</b><b>Precision</b><b>Recall</b><b>Injection safety</b></div>{Object.entries(qualityReport.perAgent).map(([agent, score]) => <div key={agent}><code>{agent}</code><span>{score.cases}</span><span>{Math.round(score.precision * 100)}%</span><span>{Math.round(score.recall * 100)}%</span><span>{Math.round(score.promptInjectionFailClosed * 100)}%</span></div>)}</div><footer><b>Live performance baseline</b><span>P50 {Math.round(liveQualityReport.scores.p50LatencyMs / 1000)}s · P95 {Math.round(liveQualityReport.scores.p95LatencyMs / 1000)}s · {liveQualityReport.scores.unauthorizedCanonicalWrites} unauthorized writes. {liveQualityReport.warnings.length ? liveQualityReport.warnings.join(" · ") : "No warnings."}</span></footer></section>
    <section className="panel ops-health-section"><header><span className="section-kicker">OPERATOR QUEUE</span><h2>Actionable health signals</h2></header>{incidents.length ? <div className="health-incidents">{incidents.map((incident) => <article key={incident.title}><span className={`health-severity health-${incident.severity}`}>{incident.severity}</span><div><b>{incident.title}</b><p>{incident.action}</p></div></article>)}</div> : <div className="health-empty"><b>No active operational incident</b><p>Availability, authentication, dead-letter and repeated-failure thresholds are defined in the operational policy.</p></div>}</section>
    <section className="panel ops-policy"><div><span>Retention</span><b>30 days successful · 90 days failed/dead letter</b></div><div><span>Authentication alert</span><b>10 failures / 5 minutes</b></div><div><span>Repeated failure alert</span><b>3 failures / 15 minutes</b></div><div><span>Owner</span><b>OET AI Suite workflow administrator</b></div></section>
  </div>;
}
