import type { AgentRunEnvelope } from "@/lib/agent-contracts";
import qualityReport from "@/data/agent-quality-report.json";
import orchestrationReport from "@/data/orchestration-quality-report.json";

const bindings = [
  ["Public orchestrator", "IEv54E2lBQyd57hY"],
  ["Governed publisher", "4czGSZtMjeGpKSFS"],
  ["Central error handler", "BkHWDRmPvXOepELU"],
] as const;

export function OperationalHealth({ runs, pendingReviews }: { runs: Array<{ run: AgentRunEnvelope }>; pendingReviews: number }) {
  const failed = runs.filter((entry) => entry.run.status === "failed");
  const incidents = [
    ...(failed.length ? [{ severity: "critical", title: `${failed.length} failed agent execution${failed.length === 1 ? "" : "s"}`, action: "Open Agent operations, assign an owner and retry or replay only after inspecting the failed step." }] : []),
    ...(pendingReviews ? [{ severity: "warning", title: `${pendingReviews} proposal set${pendingReviews === 1 ? "" : "s"} awaiting review`, action: "Complete accountable review before publication." }] : []),
  ];
  return <div className="ops-health">
    <section className="ops-health-grid">
      <article className="panel"><span className="section-kicker">RELEASE</span><h3>2026-08-11-zm-prod-05g</h3><p>Checksummed smart-orchestration baseline · endpoint contract verified</p><strong className="health-ok">Release ready</strong></article>
      <article className="panel"><span className="section-kicker">AGENT QUALITY</span><h3>{qualityReport.caseCount} cases · 6 specialists</h3><p>{qualityReport.scenarioCount} scenario classes each · {qualityReport.scores.promptInjectionFailClosed * 100}% injection fail-closed · zero unsupported claims</p><strong className={qualityReport.releaseReady ? "health-ok" : "health-warning"}>{qualityReport.releaseReady ? "Gate passed" : "Promotion blocked"}</strong></article>
      <article className="panel"><span className="section-kicker">SMART ROUTING</span><h3>{Math.round(orchestrationReport.improvements.costReduction * 100)}% less execution</h3><p>{orchestrationReport.candidate.calls}/{orchestrationReport.baseline.calls} specialist calls · {orchestrationReport.precision * 100}% precision · {orchestrationReport.recall * 100}% recall</p><strong className={orchestrationReport.qualityGatePassed ? "health-ok" : "health-warning"}>{orchestrationReport.qualityGatePassed ? "Quality preserved" : "Promotion blocked"}</strong></article>
      <article className="panel"><span className="section-kicker">INCIDENTS</span><h3>{incidents.length}</h3><p>Persistent failures and pending governance actions requiring operator attention</p><strong className={incidents.length ? "health-warning" : "health-ok"}>{incidents.length ? "Action required" : "Healthy"}</strong></article>
    </section>
    <section className="panel ops-health-section"><header><span className="section-kicker">AUTHORITATIVE BINDINGS</span><h2>Production workflow inventory</h2><p>Only these bindings are authoritative. Cleanup candidates remain non-destructive until explicitly confirmed.</p></header><div className="binding-list">{bindings.map(([name, id]) => <div key={id}><span className="health-dot"/><b>{name}</b><code>{id}</code><small>Live and release-aligned</small></div>)}</div></section>
    <section className="panel ops-health-section quality-health"><header><div><span className="section-kicker">EVALUATION READINESS</span><h2>Baseline versus candidate quality</h2><p>{qualityReport.candidate.name} compared reproducibly with {qualityReport.baseline.name}. Blocking regressions prevent promotion.</p></div><strong className={qualityReport.releaseReady ? "health-ok" : "health-warning"}>{qualityReport.releaseReady ? "Release ready" : "Blocked"}</strong></header><div className="quality-score-grid">{[["Precision", qualityReport.scores.precision, qualityReport.comparison.precision.delta], ["Recall", qualityReport.scores.recall, qualityReport.comparison.recall.delta], ["Evidence attribution", qualityReport.scores.evidenceAttribution, qualityReport.comparison.evidenceAttribution.delta], ["Reviewer acceptance", qualityReport.scores.reviewerAcceptance, qualityReport.comparison.reviewerAcceptance.delta]].map(([name, score, difference]) => <article key={String(name)}><span>{name}</span><b>{Math.round(Number(score) * 100)}%</b><small>{Number(difference) > 0 ? `+${Math.round(Number(difference) * 100)} pp improvement` : "No regression"}</small></article>)}</div><div className="quality-agent-grid"><div className="quality-agent-head"><b>Specialist</b><b>Cases</b><b>Precision</b><b>Recall</b><b>Injection safety</b></div>{Object.entries(qualityReport.perAgent).map(([agent, score]) => <div key={agent}><code>{agent}</code><span>{score.cases}</span><span>{Math.round(score.precision * 100)}%</span><span>{Math.round(score.recall * 100)}%</span><span>{Math.round(score.promptInjectionFailClosed * 100)}%</span></div>)}</div><footer><b>Regression causes</b><span>{qualityReport.regressionCauses.length ? qualityReport.regressionCauses.join(" · ") : "None. Candidate meets every blocking and warning threshold."}</span></footer></section>
    <section className="panel ops-health-section"><header><span className="section-kicker">OPERATOR QUEUE</span><h2>Actionable health signals</h2></header>{incidents.length ? <div className="health-incidents">{incidents.map((incident) => <article key={incident.title}><span className={`health-severity health-${incident.severity}`}>{incident.severity}</span><div><b>{incident.title}</b><p>{incident.action}</p></div></article>)}</div> : <div className="health-empty"><b>No active operational incident</b><p>Availability, authentication, dead-letter and repeated-failure thresholds are defined in the operational policy.</p></div>}</section>
    <section className="panel ops-policy"><div><span>Retention</span><b>30 days successful · 90 days failed/dead letter</b></div><div><span>Authentication alert</span><b>10 failures / 5 minutes</b></div><div><span>Repeated failure alert</span><b>3 failures / 15 minutes</b></div><div><span>Owner</span><b>OET AI Suite workflow administrator</b></div></section>
  </div>;
}
