"use client";

import { useState } from "react";
import type { PmoDocument } from "@/lib/pmo-schema";
import type { Scenario } from "@/lib/pmo-schema";
import { calculateCriticalPath, compareScenarios, programmeMetrics, validateProgrammeDecisionSupport } from "@/lib/programme-decision-support";

const money = (value: number) => new Intl.NumberFormat("en-GB", { style: "currency", currency: "EUR", notation: "compact", maximumFractionDigits: 1 }).format(value);

export function ProgrammeDecisionView({ data, onSaveScenario }: { data: PmoDocument; onSaveScenario: (scenario: Scenario) => void }) {
  const [editing, setEditing] = useState<Scenario | null>(null);
  const metrics = programmeMetrics(data);
  const path = calculateCriticalPath(data);
  const errors = validateProgrammeDecisionSupport(data);
  const baseline = data.scenarios.find((item) => item.status === "approved");
  const candidate = data.scenarios.find((item) => item.status === "pending_review" || item.status === "draft");
  const comparison = baseline && candidate ? compareScenarios(baseline, candidate) : undefined;
  return <div className="programme-decision">
    {errors.length > 0 && <section className="error-banner" role="alert"><span>{errors.join(" ")}</span></section>}
    <section className="panel hierarchy-card"><header><div><span className="section-kicker">GOVERNED HIERARCHY</span><h2>Portfolio and programme decision scope</h2><p>Cross-level references are validated before portfolio evidence can support a decision.</p></div><span className="status-pill status-success">{data.portfolios.length} portfolio · {data.programmes.length} programme</span></header>{data.portfolios.map((portfolio) => <article key={portfolio.id}><div><span>{portfolio.id}</span><h3>{portfolio.name}</h3><p>{portfolio.objective}</p></div><div className="hierarchy-programmes">{portfolio.programmeIds.map((programmeId) => { const programme = data.programmes.find((item) => item.id === programmeId); return programme ? <span key={programme.id}><b>{programme.name}</b><small>{programme.owner} · {programme.startDate}–{programme.endDate} · {programme.projectIds.length} project(s)</small></span> : null; })}</div></article>)}</section>
    <section className="programme-kpis"><article className="panel"><span>Forecast cost variance</span><b className={metrics.costVariance > 0 ? "negative" : "positive"}>{money(metrics.costVariance)}</b><small>{money(metrics.costForecast)} forecast vs {money(metrics.costBaseline)} baseline</small></article><article className="panel"><span>Benefit forecast gap</span><b className={metrics.benefitGap < 0 ? "negative" : "positive"}>{money(metrics.benefitGap)}</b><small>{money(metrics.benefitForecast)} forecast vs {money(metrics.benefitTarget)} target</small></article><article className="panel"><span>Capability capacity gap</span><b className={metrics.capacityGap < 0 ? "negative" : "positive"}>{metrics.capacityGap.toFixed(1)} FTE</b><small>{metrics.demand.toFixed(1)} demand vs {metrics.capacity.toFixed(1)} governed pool capacity</small></article><article className="panel"><span>Outcome forecast</span><b>{data.outcomes.filter((item) => item.status === "at_risk").length} at risk</b><small>{data.outcomes.length} governed outcome measure(s)</small></article></section>
    <section className="decision-grid"><article className="panel critical-path"><header><span className="section-kicker">DEPENDENCY NETWORK</span><h3>Explainable critical path</h3><p>{path.edges.length} governed edge(s) · {path.totalLagDays} calendar-day path</p></header><div>{path.nodes.map((node, index) => <span key={node}><b>{node}</b>{index < path.nodes.length - 1 && <i>→</i>}</span>)}{path.nodes.length === 0 && <p>No two-object schedule dependencies recorded.</p>}</div><footer><b>Calculation assumptions</b>{path.assumptions.map((assumption) => <small key={assumption}>{assumption}</small>)}</footer></article><article className="panel scenario-compare"><header><span className="section-kicker">GOVERNED SCENARIO</span><h3>Candidate versus approved baseline</h3></header>{comparison && baseline && candidate ? <><div className="scenario-head"><span><b>{baseline.title}</b>Approved · revision {baseline.baselineRevision}</span><span><b>{candidate.title}</b>{candidate.status.replaceAll("_", " ")} · baseline remains immutable</span></div><div className="scenario-deltas"><span><b>{comparison.scheduleDeltaDays} days</b>Schedule</span><span><b>{money(comparison.costDelta)}</b>Cost</span><span><b>{money(comparison.benefitDelta)}</b>Benefit</span></div><p>{candidate.rationale}</p><strong className="health-warning">Human review required before approval</strong><button className="button secondary" onClick={() => setEditing(candidate)}>Revise candidate scenario</button></> : <p>Add one approved baseline and one candidate scenario to compare impact.</p>}</article></section>
    <section className="decision-grid"><article className="panel"><header><span className="section-kicker">BENEFITS & OUTCOMES</span><h3>Value evidence</h3></header>{data.benefits.map((benefit) => <div className="decision-list-row" key={benefit.id}><span><b>{benefit.title}</b><small>{benefit.owner} · {benefit.targetDate}</small></span><strong>{money(benefit.forecast)} / {money(benefit.target)}</strong></div>)}</article><article className="panel"><header><span className="section-kicker">RESOURCE & FINANCIAL</span><h3>Non-personal capacity and actuals</h3></header>{data.resourcePools.map((pool) => <div className="decision-list-row" key={pool.id}><span><b>{pool.capability}</b><small>{pool.period} · aggregate capability pool</small></span><strong>{pool.demandFte} / {pool.capacityFte} FTE</strong></div>)}{data.financials.map((financial) => <div className="decision-list-row" key={financial.id}><span><b>{financial.title}</b><small>{financial.period} · actual {money(financial.actual || 0)}</small></span><strong>{money(financial.forecast)}</strong></div>)}</article></section>
    {editing && <ScenarioEditor scenario={editing} onClose={() => setEditing(null)} onSave={(scenario) => { onSaveScenario(scenario); setEditing(null); }}/>}  </div>;
}

function ScenarioEditor({ scenario, onClose, onSave }: { scenario: Scenario; onClose: () => void; onSave: (scenario: Scenario) => void }) {
  const [draft, setDraft] = useState(scenario);
  const number = (field: "scheduleDeltaDays" | "costDelta" | "benefitDelta", value: string) => setDraft((current) => ({ ...current, [field]: Number(value) }));
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal" onMouseDown={(event) => event.stopPropagation()} onSubmit={(event) => { event.preventDefault(); onSave({ ...draft, status: "pending_review" }); }}><header><div><span className="section-kicker">GOVERNED SCENARIO REVISION</span><h2>Revise candidate impact</h2></div><button className="icon-button" type="button" aria-label="Close scenario editor" onClick={onClose}>×</button></header><p>The approved baseline is read-only. Saving creates a new object version and audit event; human review remains required.</p><label><span>Scenario title</span><input required value={draft.title} onChange={(event) => setDraft((current) => ({ ...current, title: event.target.value }))}/></label><div className="form-row"><label><span>Schedule delta days</span><input type="number" value={draft.scheduleDeltaDays} onChange={(event) => number("scheduleDeltaDays", event.target.value)}/></label><label><span>Cost delta</span><input type="number" value={draft.costDelta} onChange={(event) => number("costDelta", event.target.value)}/></label></div><label><span>Benefit delta</span><input type="number" value={draft.benefitDelta} onChange={(event) => number("benefitDelta", event.target.value)}/></label><label><span>Impact rationale</span><textarea required value={draft.rationale} onChange={(event) => setDraft((current) => ({ ...current, rationale: event.target.value }))}/></label><footer><button type="button" className="button ghost" onClick={onClose}>Cancel</button><button className="button primary">Save governed revision</button></footer></form></div>;
}
